/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Voucher;
import modelViews.QlKhachHang;
import modelViews.QlVoucher;
import service.khachhangservice.IKhachHangServise;
import service.khachhangservice.impl.KhachHangServise;
import util.DBConnect;
import util.Uhelper;

/**
 *
 * @author bcuon
 */
public class ViewKhachHang extends javax.swing.JPanel {

    private IKhachHangServise _khHangServise = new KhachHangServise();

    public ViewKhachHang() {
        initComponents();
        load(_khHangServise.selectAll());
    }

    private void load(ArrayList<QlKhachHang> ds) {
        DefaultTableModel model = (DefaultTableModel) tblKhachhang.getModel();
        model.setRowCount(0);
        for (QlKhachHang kh : ds) {
            Object[] row = {
                kh.getMaKh(),
                kh.getTenKh(),
                kh.getGioiTinh() ? "Nam" : "Nữ",
                kh.getSdt(),
                kh.getEmail(),
                kh.getDiaChi(),
                kh.getNgaySinh()
            };
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMakh = new textfield.TextField2();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenkh = new textfield.TextField2();
        txtNgaysinh = new textfield.TextField2();
        jLabel8 = new javax.swing.JLabel();
        txtDiachi = new textfield.TextField2();
        jLabel4 = new javax.swing.JLabel();
        txtsdt = new textfield.TextField2();
        jLabel7 = new javax.swing.JLabel();
        rdoNam = new radio_button.RadioButtonCustom();
        rdoNu = new radio_button.RadioButtonCustom();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new textfield.TextField2();
        jPanel21 = new javax.swing.JPanel();
        bnSua = new app.view.swing.ButtonGradient();
        btnXoa = new app.view.swing.ButtonGradient();
        btnThem = new app.view.swing.ButtonGradient();
        btnLammoi = new app.view.swing.ButtonGradient();
        btnLoad = new app.view.swing.ButtonGradient();
        jPanel8 = new javax.swing.JPanel();
        txtTimkiem = new textfield.TextField2();
        jLabel11 = new javax.swing.JLabel();
        cboLoctheoGT = new app.view.swing.ComboBoxSuggestion();
        btnTimkiem = new app.view.swing.ButtonGradient();
        scrollPaneWin111 = new custome_ui.swing.ScrollPaneWin11();
        tblKhachhang = new rojeru_san.complementos.RSTableMetro();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 28, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jPanel2.setBackground(new java.awt.Color(38, 28, 73));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(38, 28, 73));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(38, 28, 73));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(38, 28, 73));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã KH");

        txtMakh.setForeground(new java.awt.Color(0, 0, 0));
        txtMakh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày sinh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên KH");

        txtTenkh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNgaysinh.setForeground(new java.awt.Color(0, 0, 0));
        txtNgaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaysinhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SĐT");

        txtDiachi.setForeground(new java.awt.Color(0, 0, 0));
        txtDiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        txtsdt.setForeground(new java.awt.Color(0, 0, 0));
        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Giới tính");

        rdoNam.setBackground(new java.awt.Color(38, 28, 73));
        buttonGroup1.add(rdoNam);
        rdoNam.setForeground(new java.awt.Color(255, 255, 255));
        rdoNam.setText("Nam");
        rdoNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });

        rdoNu.setBackground(new java.awt.Color(38, 28, 73));
        buttonGroup1.add(rdoNu);
        rdoNu.setForeground(new java.awt.Color(255, 255, 255));
        rdoNu.setText("Nữ");
        rdoNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Địa chỉ");

        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMakh, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtTenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)
                        .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)))
                .addGap(49, 49, 49)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(38, 28, 73));

        bnSua.setForeground(new java.awt.Color(0, 0, 0));
        bnSua.setText("Sửa");
        bnSua.setColor1(new java.awt.Color(255, 255, 255));
        bnSua.setColor2(new java.awt.Color(102, 102, 102));
        bnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSuaActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setText("Xóa");
        btnXoa.setColor1(new java.awt.Color(255, 255, 255));
        btnXoa.setColor2(new java.awt.Color(102, 102, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setText("Thêm");
        btnThem.setColor1(new java.awt.Color(255, 255, 255));
        btnThem.setColor2(new java.awt.Color(102, 102, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLammoi.setForeground(new java.awt.Color(0, 0, 0));
        btnLammoi.setText("Làm mới");
        btnLammoi.setColor1(new java.awt.Color(255, 255, 255));
        btnLammoi.setColor2(new java.awt.Color(102, 102, 102));
        btnLammoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnLoad.setForeground(new java.awt.Color(0, 0, 0));
        btnLoad.setText("Load");
        btnLoad.setColor1(new java.awt.Color(255, 255, 255));
        btnLoad.setColor2(new java.awt.Color(102, 102, 102));
        btnLoad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(bnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1310, 260));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 250));

        jPanel8.setBackground(new java.awt.Color(38, 28, 73));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        txtTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lọc");

        cboLoctheoGT.setBackground(new java.awt.Color(38, 28, 73));
        cboLoctheoGT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cboLoctheoGT.setForeground(new java.awt.Color(255, 255, 255));
        cboLoctheoGT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));
        cboLoctheoGT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoctheoGT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoctheoGTItemStateChanged(evt);
            }
        });
        cboLoctheoGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoctheoGTActionPerformed(evt);
            }
        });

        btnTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setColor1(new java.awt.Color(255, 255, 255));
        btnTimkiem.setColor2(new java.awt.Color(102, 102, 102));
        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        tblKhachhang.setAutoCreateRowSorter(true);
        tblKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Giới tính", "SĐT", "Email", "Địa chỉ", "Ngày sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachhang.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblKhachhang.setColorBordeFilas(new java.awt.Color(153, 153, 153));
        tblKhachhang.setColorBordeHead(new java.awt.Color(153, 153, 153));
        tblKhachhang.setColorFilasBackgound1(new java.awt.Color(204, 204, 204));
        tblKhachhang.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblKhachhang.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblKhachhang.setColorSelBackgound(new java.awt.Color(38, 28, 73));
        tblKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachhang.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachhang.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachhang.setFuenteHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachhang.setRowHeight(30);
        tblKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachhangMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tblKhachhang);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel11)
                        .addGap(35, 35, 35)
                        .addComponent(cboLoctheoGT, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 1275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoctheoGT, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 1300, 510));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 790));
    }// </editor-fold>//GEN-END:initComponents

    private QlKhachHang getForm() {
        try {
            QlKhachHang kh = new QlKhachHang();
            kh.setMaKh(txtMakh.getText());
            kh.setTenKh(txtTenkh.getText());
            kh.setGioiTinh(rdoNam.isSelected());
            kh.setSdt(txtsdt.getText());
            kh.setEmail(txtemail.getText());
            kh.setDiaChi(txtDiachi.getText());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            Date ngaySinh;
            ngaySinh = dateFormat.parse(txtNgaysinh.getText());

            kh.setNgaySinh(ngaySinh);

            return kh;

        } catch (ParseException ex) {
            Logger.getLogger(ViewKhachHang.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        return null;

    }

    private Boolean validateFormKhachHang() {

        if (Uhelper.checkNull(txtTenkh, "Nhập tên voucher")) {
            return true;
        }
        if (Uhelper.checkNull(txtMakh, "Nhập mã")) {
            return true;
        }
        if (Uhelper.checkKyTuDacBiet(txtMakh, "Nhập mã chỉ có chữ cái và số")) {
            return true;
        }

        if (Uhelper.checkNull(txtNgaysinh, "Nhập ngày sinh")) {
            return true;
        }

        if (Uhelper.checkNull(txtDiachi, "Nhập địa chỉ")) {
            return true;
        }
        if (Uhelper.checkNull(txtemail, "Nhập địa chỉ")) {
            return true;
        }
        if (Uhelper.checkNull(txtsdt, "Nhập số điện thoại")) {
            return true;
        }
        if (Uhelper.checkSDT(txtsdt, "Nhập số điện thoại đúng định dạng 9-10 số")) {
            return true;
        }
        if (Uhelper.checkEmail(txtemail, "Nhập email đúng định dạng 9-10 số")) {
            return true;
        }

        return false;
    }

    private boolean checkTrung(String ma) {
        boolean kq = false;//mặc định kết quả là không trùng
        for (int i = 0; i < tblKhachhang.getRowCount(); i++) {
            if (tblKhachhang.getValueAt(i, 0).toString().equalsIgnoreCase(ma)) {
                kq = true;
            }
        }
        return kq;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkTrung(txtMakh.getText())) {
            JOptionPane.showMessageDialog(this, "Trùng mã");
            return;
        }
        if (validateFormKhachHang()) {
            return;
        }
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse(txtNgaysinh.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày nhập vào không đúng định dạng");
            txtNgaysinh.requestFocus();
            return;
        }
        try {
            QlKhachHang qlKhachHang = getForm();
            if (_khHangServise.insert(qlKhachHang) != null) {
                JOptionPane.showMessageDialog(this, "Thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
            load(_khHangServise.selectAll());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void showDetail() {
        try {
            int selectedRow = tblKhachhang.getSelectedRow();
            txtMakh.setText(tblKhachhang.getValueAt(selectedRow, 0).toString());
            txtTenkh.setText(tblKhachhang.getValueAt(selectedRow, 1).toString());

            String gioiTinh = (String) tblKhachhang.getValueAt(selectedRow, 2);

            if (gioiTinh.equals("Nam")) {
                rdoNam.setSelected(true);
            } else {
                rdoNu.setSelected(true);
            }
            txtsdt.setText(tblKhachhang.getValueAt(selectedRow, 3).toString());
            txtemail.setText(tblKhachhang.getValueAt(selectedRow, 4).toString());
            txtDiachi.setText(tblKhachhang.getValueAt(selectedRow, 5).toString());

            txtNgaysinh.setText(tblKhachhang.getValueAt(selectedRow, 6).toString());

        } catch (Exception e) {
        }

    }


    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tblKhachhang.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa");
            return;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        QlKhachHang ql = getForm();
        String maCanXoa = getMa();
        if (_khHangServise.delete(maCanXoa) != null) {
            JOptionPane.showMessageDialog(this, " Xóa Thành công");
        } else {
            JOptionPane.showMessageDialog(this, " Xóa Thất bại");
        }
        load(_khHangServise.selectAll());
    }//GEN-LAST:event_btnXoaActionPerformed
    private String getMa() {
        int row = tblKhachhang.getSelectedRow();
        String ma = tblKhachhang.getValueAt(row, 0).toString();
        return ma;
    }
    private void bnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSuaActionPerformed
        int selectedRow = tblKhachhang.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa");
            return;
        }
        QlKhachHang kh = getForm();
        String ma = getMa();
        kh.setMaKh(ma);
        if (validateFormKhachHang()) {
            return;
        }
        if (_khHangServise.update(kh) != null) {
            JOptionPane.showMessageDialog(this, "Thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại");
        }
        load(_khHangServise.selectAll());
    }//GEN-LAST:event_bnSuaActionPerformed
    private ArrayList<QlKhachHang> getListKhWhenSearch(String input) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;

        ArrayList<QlKhachHang> listKh = new ArrayList<>();
        ArrayList<QlKhachHang> lstByMa = new ArrayList<>();
        ArrayList<QlKhachHang> lstByName = new ArrayList<>();
        if (!input.trim().matches("[0-9]+")) {
            lstByName = _khHangServise.getAllKhByMa0(input);
            listKh.addAll(lstByName);
        }

        lstByMa = _khHangServise.getAllKhByNameKM0(input);
        listKh.addAll(lstByMa);

        if (listKh.size() == 0) {
            load(listKh);
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng");
        } else {
            if (lstByMa.size() != 0) {
                load(_khHangServise.getAllKhByMa0(input));
            }
            if (lstByName.size() != 0) {
                load(_khHangServise.getAllKhByNameKM0(input));
            }

        }
        return listKh;
    }
    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;
        String input = txtTimkiem.getText();

        ArrayList<QlKhachHang> listKhachHang = new ArrayList<>();
        ArrayList<QlKhachHang> lstByMa = new ArrayList<>();
        ArrayList<QlKhachHang> lstByName = new ArrayList<>();

        lstByMa = _khHangServise.getAllKhByMa0(input);
        listKhachHang.addAll(lstByMa);

        if (listKhachHang.size() == 0) {
            load(listKhachHang);
            JOptionPane.showMessageDialog(this, "Không tìm thấy Khách hàng");
        } else {

            if (lstByMa.size() != 0) {
                load(_khHangServise.getAllKhByMa0(input));
            }
            if (lstByName.size() != 0) {
                load(_khHangServise.getAllKhByNameKM0(input));
            }

        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void cboLoctheoGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoctheoGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoctheoGTActionPerformed

    private void tblKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachhangMouseClicked
        showDetail();
    }//GEN-LAST:event_tblKhachhangMouseClicked
    private void clear() {
        txtTenkh.setText("");
        txtMakh.setText("");
        txtDiachi.setText("");
        txtNgaysinh.setText("");
        txtTimkiem.setText("");
        txtemail.setText("");
        txtsdt.setText("");
    }
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        clear();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        load(_khHangServise.selectAll());
    }//GEN-LAST:event_btnLoadActionPerformed
    private void loadDataLocGioiTinh() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblKhachhang.getModel();

            Connection connection = DBConnect.getConnection();
            String sql = "SELECT ma, ten, sdt, email, diaChi, gioiTinh, ngaySinh \n"
                    + "FROM KhachHang WHERE gioiTinh = ?";

            boolean gioiTinhValue = "Nam".equals(cboLoctheoGT.getSelectedItem().toString());

            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setBoolean(1, gioiTinhValue);
            ResultSet rs = statement.executeQuery();

            model.setColumnCount(0);
            model.addColumn("Mã Kh");
            model.addColumn("Tên Kh");
            model.addColumn("Giới tính");
            model.addColumn("SDT");
            model.addColumn("Email");
            model.addColumn("Địa chỉ");
            model.addColumn("Ngày sinh");
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ma"),
                    rs.getString("ten"),
                    rs.getBoolean("gioiTinh") ? "Nam" : "Nữ",
                    rs.getString("sdt"),
                    rs.getString("email"),
                    rs.getString("diaChi"),
                    rs.getDate("ngaySinh")
                });
            }

            statement.clearParameters();
            connection.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void cboLoctheoGTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoctheoGTItemStateChanged
        // TODO add your handling code here:
        loadDataLocGioiTinh();
    }//GEN-LAST:event_cboLoctheoGTItemStateChanged

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtNgaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaysinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.swing.ButtonGradient bnSua;
    private app.view.swing.ButtonGradient btnLammoi;
    private app.view.swing.ButtonGradient btnLoad;
    private app.view.swing.ButtonGradient btnThem;
    private app.view.swing.ButtonGradient btnTimkiem;
    private app.view.swing.ButtonGradient btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private app.view.swing.ComboBoxSuggestion cboLoctheoGT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private radio_button.RadioButtonCustom rdoNam;
    private radio_button.RadioButtonCustom rdoNu;
    private custome_ui.swing.ScrollPaneWin11 scrollPaneWin111;
    private rojeru_san.complementos.RSTableMetro tblKhachhang;
    private textfield.TextField2 txtDiachi;
    private textfield.TextField2 txtMakh;
    private textfield.TextField2 txtNgaysinh;
    private textfield.TextField2 txtTenkh;
    private textfield.TextField2 txtTimkiem;
    private textfield.TextField2 txtemail;
    private textfield.TextField2 txtsdt;
    // End of variables declaration//GEN-END:variables
}
